version: '3'

services:
  php:
    image: demo/php
    build:
      context: .
      dockerfile: ./php/Dockerfile
      target: dev
      args:
        - COMPOSER_VERSION
        - PHP_VERSION
    volumes:
      - ./src:/var/www:cached
    networks:
      php:

  nginx:
    image: demo/nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - NGINX_VERSION
    volumes:
      - ./src:/var/www:ro
    networks:
      php:
    ports:
      - 8082:80
    depends_on:
      - php

networks:
  php:
